# Generated by Django 3.0.6 on 2022-11-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=70)),
                ('lifetimevalue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datejoined', models.DateTimeField(null=True)),
                ('notes', models.CharField(max_length=70)),
                ('emailaddress', models.CharField(max_length=70)),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('jobtitle', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
                ('mobilephone', models.CharField(max_length=70)),
                ('workphone', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('stateprovince', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('zip', models.CharField(max_length=70)),
                ('website', models.CharField(max_length=70)),
                ('stopmethod', models.CharField(max_length=70)),
                ('confirmquestionmark', models.CharField(max_length=70)),
                ('addmethod', models.CharField(max_length=70)),
                ('signupsource', models.CharField(max_length=70)),
                ('totalreviewsleft', models.CharField(max_length=70)),
                ('lastemailratingdone', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Customfeild',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('customfeildintvalue', models.IntegerField()),
                ('customfeildstringvalue', models.CharField(max_length=70)),
                ('dateofcreation', models.DateTimeField(null=True)),
                ('lastcustomfeildupdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachedtag',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('dateofattachement', models.DateTimeField(null=True)),
                ('contactid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Contact')),
                ('tagid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Attachedcustomfeild',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('dateofattachement', models.DateTimeField(null=True)),
                ('contactid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Contact')),
                ('customfeildid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Customfeild')),
            ],
        ),
    ]
