# Generated by Django 3.0.6 on 2022-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_attachedform_attachedgroup_form_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('emailaddress', models.CharField(max_length=70)),
                ('industry', models.CharField(max_length=70)),
            ],
        ),
    ]
