# Generated by Django 3.0.6 on 2022-11-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='username',
        ),
    ]
