# Generated by Django 3.0.6 on 2022-11-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20221126_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimport',
            name='staffid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Staff'),
        ),
    ]
