# Generated by Django 3.0.6 on 2022-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20221126_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='numberofsubscribes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='totalsubscribes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
