# Generated by Django 3.0.6 on 2022-11-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20221126_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachedgroup',
            unique_together={('id', 'dateofattachement', 'contactid', 'groupid')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('id', 'name', 'dateofcreation', 'type', 'numberofsubscribes', 'numberofunsubscribes', 'totalsubscribes')},
        ),
    ]
