# Generated by Django 3.0.6 on 2022-11-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20221127_0513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachedform',
            unique_together={('id', 'dateofattachement', 'contactid', 'formid')},
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('id', 'name', 'dateofcreation', 'status', 'numberofsubscribes', 'totalsubscribes')},
        ),
    ]
