# Generated by Django 3.0.6 on 2022-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20221129_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimport',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bulkimport',
            name='filename',
            field=models.CharField(max_length=70),
        ),
    ]
