# Generated by Django 3.0.6 on 2022-11-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20221129_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkimport',
            name='attachedall',
        ),
        migrations.AddField(
            model_name='attachedall',
            name='bulkimportid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Bulkimport'),
        ),
    ]
