# Generated by Django 3.0.6 on 2022-11-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20221129_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bulkimport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
