# Generated by Django 3.0.6 on 2023-01-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20221129_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedall',
            name='staffid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Staff'),
        ),
    ]
