# Generated by Django 3.0.6 on 2023-01-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_attachedall_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='staffid',
        ),
    ]
