# Generated by Django 3.0.6 on 2023-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20230130_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('id', 'status', 'lifetimevalue', 'datejoined', 'notes', 'emailaddress', 'firstname', 'lastname', 'jobtitle', 'company', 'mobilephone', 'workphone', 'country', 'stateprovince', 'city', 'address', 'zip', 'website', 'stopmethod', 'confirmquestionmark', 'addmethod', 'signupsource', 'totalreviewsleft', 'lastemailratingdone')},
        ),
    ]
