# Generated by Django 3.0.6 on 2023-02-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20230212_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('dateone', models.DateTimeField(null=True)),
                ('datetwo', models.DateTimeField(null=True)),
                ('dateofcreation', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachedsegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateofattachement', models.DateTimeField(null=True)),
                ('segmentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Segment')),
            ],
        ),
    ]
