# Generated by Django 3.0.6 on 2023-09-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_joinstaffcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinStaffCustomfeild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customfeildid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Customfeild')),
                ('staffid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Staff')),
            ],
        ),
    ]
