# Generated by Django 3.0.6 on 2023-09-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_joinstaffcustomfeild'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfeild',
            unique_together={('id', 'name', 'customfeildintvalue', 'customfeildstringvalue', 'dateofcreation', 'lastcustomfeildupdate')},
        ),
        migrations.AlterUniqueTogether(
            name='joinstaffcustomfeild',
            unique_together={('id', 'staffid', 'customfeildid')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('id', 'userid', 'username', 'firstname', 'lastname', 'emailaddress', 'industry')},
        ),
    ]
