# Generated by Django 3.0.6 on 2023-09-30 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20230927_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedsegment',
            name='staffid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Staff'),
        ),
    ]
