# Generated by Django 3.0.6 on 2023-12-12 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0036_attachedemail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastmessage', models.CharField(default=' ', max_length=255)),
                ('lastsentuserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'lastmessage', 'lastsentuserid')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(default=' ', max_length=255)),
                ('dateofcreation', models.DateTimeField(null=True)),
                ('inboxid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Inbox')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'inboxid', 'userid', 'message', 'dateofcreation')},
            },
        ),
        migrations.CreateModel(
            name='Inboxparticipants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inboxid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Inbox')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'inboxid', 'userid')},
            },
        ),
    ]
