# Generated by Django 3.0.6 on 2023-12-13 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0037_inbox_inboxparticipants_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together={('id', 'lastmessage', 'userid')},
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='lastsentuserid',
        ),
    ]
