"""
Django settings for mailp project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from django.contrib.messages import constants as messages
import os







# Build paths inside the project like this: BASE_DIR / 'subdir'.

#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))





EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'ae30c81fcfa156'
EMAIL_HOST_PASSWORD = 'db1462228c8403'
EMAIL_PORT = '2525'



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9k^fw-v1sce4fk+=*e6gbd5hbi*z6ul_u&dr!dbh02cb1k)ri4"

#SECRET_KEY =""
#SECRET_KEY = ""
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
#when degub is true, the static pictures & css started showing again rather than not showing
#i found this sollution to the problem here https://stackoverflow.com/questions/60620434/django-cannot-find-static-files
#'DEBUG =True ' is only for when your debuging on your own not when you want to deploy
#so make the necessary correction to 'DEBUG - False' when you decide to deploy
#DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['mpmp-env.eba-7dkurhg2.us-east-2.elasticbeanstalk.com','jumboenv.eba-bxb7n3aa.us-east-2.elasticbeanstalk.com', 'jumboenv2.eba-bxb7n3aa.us-east-2.elasticbeanstalk.com','MailPinyata3-dev.us-east-2.elasticbeanstalk.com','*','localhost', '127.0.0.1', '5432']

# i just added the below code
# Application definition
BOWER_COMPONENTS_ROOT = '/PROJECT_ROOT/components/'
BOWER_INSTALLED_APPS = (
    'jquery',
    'jquery-ui',
    'bootstrap'
)

# i just added the above code

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pages",
    "rest_framework",
    #"pages.apps.PagesConfig",
    #'schedule',
    #'djangobower',
    #'rest_framework',
    #"form.apps.FormConfig",
    #'widget_tweaks',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mailp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request"
            ],
        },
    },
]

WSGI_APPLICATION = "mailp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#if you change the database name django will create a new database
#for you

DATABASES = {
    "default": {
        #"ENGINE": "django.db.backends.sqlite3",
        "ENGINE": 'django.db.backends.postgresql',
        #"NAME": BASE_DIR / "db.sqlite3",
        #'NAME': os.path.join(BASE_DIR , 'db.sqlite3'),

        "NAME": 'mailpdatabase',
        'USER': 'postgres',
        'PASSWORD': 'mailp2020!',
        #'HOST':'mailpdatabasei.cbla1ovjyisy.us-east-2.rds.amazonaws.com',
        'HOST':'mailpdatabasei.chu2n64apc5u.us-east-2.rds.amazonaws.com',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = "/static/"

#ok this finally works now that i moved the static files inside the mailp folder instead of putting it outside that
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mailp/static'),
]





#i need to add these static finders so it works 100% of the time & so the static LOADS ACTUALLY
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# (down)from other project



# (up)from other project